spring.application.name=vari-backend

# 1. URL: USE THE POOLER (Required for your WiFi)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres

# 2. CREDENTIALS (Long Username is Required)

spring.datasource.username=postgres.lwqkvblnvpalvrefnnnv
spring.datasource.password=AsthaTrivedi
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. HIBERNATE TWEAKS (Required for Pooler Stability)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. CONNECTION POOL SETTINGS (Prevents disconnects)
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.connection-timeout=30000

server.port=8080